[server]
headless = true
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true

[theme]
primaryColor = "#217346"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#333333"
